ASoC: es8316: add missing include
sound/soc/codecs/es8316.c:589:15: error: implicit declaration of function ‘irq_get_trigger_type’; did you mean ‘irq_get_irqchip_state’? [-Werror=implicit-function-declaration]
               irq_get_trigger_type(es8316->hp_irq) | IRQF_ONESHOT,
               ^~~~~~~~~~~~~~~~~~~~
               irq_get_irqchip_state

Signed-off-by: youling257 <youling257@gmail.com>